### ISSUE TITLE
support codes containing locks

### ISSUE THREAD

**Issue by laprej** [pschanely/CrossHair#146]
**Is your feature request related to a problem? Please describe.**
Many code bases include locking, e.g., threading.Rlock(), multiprocessing.RLock(), etc.  At the moment these constructs seem to break Crosshair.

For example, when trying to generate covering test cases:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/laprej/psh/git/.virtualenv3/lib/python3.9/site-packages/crosshair/__main__.py", line 8, in <module>
    crosshair.main.main()
  File "/home/laprej/psh/git/.virtualenv3/lib/python3.9/site-packages/crosshair/main.py", line 642, in main
    sys.exit(unwalled_main(cmd_args))
  File "/home/laprej/psh/git/.virtualenv3/lib/python3.9/site-packages/crosshair/main.py", line 608, in unwalled_main
    return cover(args, defaults.overlay(options), sys.stdout, sys.stderr)
  File "/home/laprej/psh/git/.virtualenv3/lib/python3.9/site-packages/crosshair/main.py", line 537, in cover
    paths = path_cover(ctxfn, options, args.coverage_type)
  File "/home/laprej/psh/git/.virtualenv3/lib/python3.9/site-packages/crosshair/path_cover.py", line 103, in path_cover
    summary = run_iteration(fn, sig, space)
  File "/home/laprej/psh/git/.virtualenv3/lib/python3.9/site-packages/crosshair/path_cover.py", line 54, in run_iteration
    pre_args = copy.deepcopy(args)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.RLock' object
```

**Describe the solution you'd like**
I would like for them to be supported correctly.

**Describe alternatives you've considered**
Incremental support would be great as well.  For example, inserting a no-op would obviously be incorrect but should allow Crosshair to continue instead of error out.

**Comment by pschanely** [comment]
Thank you for reporting this!
Indeed, I think the fix is straightforward. It's on the top of my queue.

**Comment by pschanely** [comment]
Hopefully this is fixed in 0.0.20!

We should now essentially try to skip copying any uncopyable object, not just locks.  [Here is the kind of example](https://crosshair-web.org/?crosshair=0.1&python=3.8&gist=b3a6311215ec2b652ee7067691a5482a) I had imagined while working on this issue, but your situation may have had additional complications, so it would be amazing if you could give it a try and report back!

**Comment by laprej** [comment]
Maybe something more along the lines of [this?](https://crosshair-web.org/?crosshair=0.1&python=3.8&gist=0ed7e709710993799ab2edc0777ca297)

**Comment by pschanely** [comment]
> Maybe something more along the lines of [this?](https://crosshair-web.org/?crosshair=0.1&python=3.8&gist=0ed7e709710993799ab2edc0777ca297)

Yup! Hopefully, the counterexample given is what you expected.  (re-open if not!) One thing to point out: CrossHair doesn't do anything useful over code that spawns multiple threads, and I suspect will likely fail with a nondeterminism exception. But locks should still "work" as expected in the single thread case.

Presumably, you encountered this problem in the context of some larger work, so I hope that is going well for you too - let me know in a [discussion](https://github.com/pschanely/CrossHair/discussions) or [chat](https://gitter.im/Cross_Hair/Lobby)!
