### ISSUE TITLE
z3 boolean isn't number-comparable

### ISSUE THREAD

**Issue by pschanely** [pschanely/CrossHair#283]
[from `test_assume_has_status_reason`:](https://github.com/HypothesisWorks/hypothesis/actions/runs/10046646626/job/27766587120?pr=4034#step:6:3400)

```python-traceback
Traceback (most recent call last):
  File ".../crosshair/libimpl/builtinslib.py", line 900, in __abs__
    return self._unary_op(lambda v: z3.If(v < 0, -v, v))
  File ".../crosshair/libimpl/builtinslib.py", line 319, in _unary_op
    return self.__class__(op(self.var), self.python_type)
  File ".../crosshair/libimpl/builtinslib.py", line 900, in <lambda>
    return self._unary_op(lambda v: z3.If(v < 0, -v, v))
TypeError: '<' not supported between instances of 'BoolRef' and 'int'
```

whereas in Python `issubclass(bool, int)` and so you can indeed compare them.

_Originally posted by @Zac-HD in https://github.com/HypothesisWorks/hypothesis/issues/4034#issuecomment-2243950206_

**Comment by pschanely** [comment]
Ooops! Never closed this out. It was fixed way back in [v0.0.65](https://crosshair.readthedocs.io/en/latest/changelog.html#version-0-0-65)
