### ISSUE TITLE
Error installing from PyPI

### ISSUE THREAD

**Issue by jretz** [pschanely/CrossHair#330]
Installing into a new `venv` using `pip` fails with a `zipfile.BadZipFile` error:

```
$ cd /tmp
$ mkdir x
$ cd x
$ python3 -m venv venv
$ venv/bin/pip install crosshair-tool
Collecting crosshair-tool
  Downloading crosshair_tool-0.0.80-cp39-cp39-macosx_11_0_arm64.whl (503 kB)
     |████████████████████████████████| 503 kB 3.7 MB/s
Collecting pygls>=1.0.0
  Downloading pygls-1.3.1-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 8.0 MB/s
Collecting typing_extensions>=3.10.0
  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting typeshed-client>=2.0.5
  Downloading typeshed_client-2.7.0-py3-none-any.whl (624 kB)
     |████████████████████████████████| 624 kB 8.0 MB/s
Collecting typing-inspect>=0.7.1
  Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting importlib_metadata>=4.0.0
  Downloading importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Collecting z3-solver>=4.13.0.0
  Downloading z3_solver-4.13.4.0-py3-none-macosx_13_0_arm64.whl (36.9 MB)
     |████████████████████████████████| 36.9 MB 2.5 MB/s
Collecting packaging
  Downloading packaging-24.2-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 8.4 MB/s
Collecting zipp>=3.20
  Downloading zipp-3.21.0-py3-none-any.whl (9.6 kB)
Collecting lsprotocol==2023.0.1
  Downloading lsprotocol-2023.0.1-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 11.8 MB/s
Collecting cattrs>=23.1.2
  Downloading cattrs-24.1.2-py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 6.7 MB/s
Collecting attrs>=21.3.0
  Downloading attrs-24.3.0-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 6.1 MB/s
Collecting exceptiongroup>=1.1.1
  Downloading exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Collecting importlib-resources>=1.4.0
  Downloading importlib_resources-6.4.5-py3-none-any.whl (36 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: typing-extensions, exceptiongroup, attrs, zipp, cattrs, mypy-extensions, lsprotocol, importlib-resources, z3-solver, typing-inspect, typeshed-client, pygls, packaging, importlib-metadata, crosshair-tool
ERROR: Exception:
Traceback (most recent call last):
  File "/private/tmp/x/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/private/tmp/x/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/private/tmp/x/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 390, in run
    installed = install_given_reqs(
  File "/private/tmp/x/venv/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/private/tmp/x/venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 758, in install
    install_wheel(
  File "/private/tmp/x/venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 794, in install_wheel
    _install_wheel(
  File "/private/tmp/x/venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 637, in _install_wheel
    file.save()
  File "/private/tmp/x/venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 406, in save
    shutil.copyfileobj(f, dest)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/zipfile.py", line 922, in read
    data = self._read1(n)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1012, in _read1
    self._update_crc(data)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/zipfile.py", line 940, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'crosshair/tools/generate_demo_table.py'
```

Installing directly from the main branch on GitHub works fine:

```
$ cd /tmp
$ mkdir x
$ cd x
$ python3 -m venv venv
$ venv/bin/pip install "git+https://github.com/pschanely/CrossHair.git"
Collecting git+https://github.com/pschanely/CrossHair.git
  Cloning https://github.com/pschanely/CrossHair.git to /private/var/folders/l3/wmz3xbjn11j4dqtw54k8f__c0000gp/T/pip-req-build-oijtbso6
  Running command git clone -q https://github.com/pschanely/CrossHair.git /private/var/folders/l3/wmz3xbjn11j4dqtw54k8f__c0000gp/T/pip-req-build-oijtbso6
  Resolved https://github.com/pschanely/CrossHair.git to commit 410f8224f043fdfb8c6d2efc6730eae7a88564b1
Collecting packaging
  Using cached packaging-24.2-py3-none-any.whl (65 kB)
Collecting typing-inspect>=0.7.1
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting typing_extensions>=3.10.0
  Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting z3-solver>=4.13.0.0
  Using cached z3_solver-4.13.4.0-py3-none-macosx_13_0_arm64.whl (36.9 MB)
Collecting importlib_metadata>=4.0.0
  Using cached importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Collecting pygls>=1.0.0
  Using cached pygls-1.3.1-py3-none-any.whl (56 kB)
Collecting typeshed-client>=2.0.5
  Using cached typeshed_client-2.7.0-py3-none-any.whl (624 kB)
Collecting zipp>=3.20
  Using cached zipp-3.21.0-py3-none-any.whl (9.6 kB)
Collecting cattrs>=23.1.2
  Using cached cattrs-24.1.2-py3-none-any.whl (66 kB)
Collecting lsprotocol==2023.0.1
  Using cached lsprotocol-2023.0.1-py3-none-any.whl (70 kB)
Collecting attrs>=21.3.0
  Using cached attrs-24.3.0-py3-none-any.whl (63 kB)
Collecting exceptiongroup>=1.1.1
  Using cached exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Collecting importlib-resources>=1.4.0
  Using cached importlib_resources-6.4.5-py3-none-any.whl (36 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Using legacy 'setup.py install' for crosshair-tool, since package 'wheel' is not installed.
Installing collected packages: typing-extensions, exceptiongroup, attrs, zipp, cattrs, mypy-extensions, lsprotocol, importlib-resources, z3-solver, typing-inspect, typeshed-client, pygls, packaging, importlib-metadata, crosshair-tool
    Running setup.py install for crosshair-tool ... done
Successfully installed attrs-24.3.0 cattrs-24.1.2 crosshair-tool-0.0.80 exceptiongroup-1.2.2 importlib-metadata-8.5.0 importlib-resources-6.4.5 lsprotocol-2023.0.1 mypy-extensions-1.0.0 packaging-24.2 pygls-1.3.1 typeshed-client-2.7.0 typing-extensions-4.12.2 typing-inspect-0.9.0 z3-solver-4.13.4.0 zipp-3.21.0
```

**Comment by pschanely** [comment]
Thank you for this report; I can reproduce the issue.

It seems like a corrupted wheel file. Oddly, it looks like cibuildwheel in GitHub actionswas able to install this wheel and run tests. I am still investigating, but in the meantime, I've deleted the package, which should make people fall back to building from source. More soon, and thanks again!

**Comment by pschanely** [comment]
I've re-packaged in [v0.0.81](https://pypi.org/project/crosshair-tool/0.0.81/); hopefully we won't have this issue again.

I upgraded to PyPI's "trusted publishing" while I'm at it, which now tracks provenance [details](https://pypi.org/project/crosshair-tool/#crosshair_tool-0.0.81-cp38-cp38-macosx_11_0_arm64.whl) - neat stuff!
