### ISSUE TITLE
Additional information for non-descriptive stack trace

### ISSUE THREAD

**Issue by CoenSchalkwijk** [pschanely/CrossHair#35]
**Is your feature request related to a problem? Please describe.**
When running into a NameError, in case of a missing import, the resulting stack trace shows the affected class but lacks detail information to pinpoint the location of the line number or function name of the class under inspection. 

For example: 

```Process Process-4147:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/main.py", line 118, in pool_worker_main
    messages = analyze_any(module, options)
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/core.py", line 536, in analyze_any
    return analyze_module(cast(types.ModuleType, entity), options)
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/core.py", line 546, in analyze_module
    messages.extend(analyze_any(member, options))
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/core.py", line 525, in analyze_any
    return analyze_class(cast(Type, entity), options)
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/core.py", line 572, in analyze_class
    class_conditions = get_class_conditions(cls)
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/util.py", line 197, in memo_wrapper
    saved[a] = f(a)
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/condition_parser.py", line 359, in get_class_conditions
    parsed_conditions = get_fn_conditions(method, self_type=cls)
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/condition_parser.py", line 273, in get_fn_conditions
    sig = resolve_signature(fn)
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/condition_parser.py", line 193, in resolve_signature
    type_hints = get_type_hints(fn, fn_globals(fn))
  File "/usr/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'BarFoo' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/main.py", line 121, in pool_worker_main
    raise CrosshairInternal(
crosshair.util.CrosshairInternal: Worker failed while analyzing ./foo/bar/fooBar.py
```

**Describe the solution you'd like**
I'd like to see a line number or function name, when available (and sensible of course)

**Describe alternatives you've considered**
It might be that my claim is not sensible: it could always be the __init__, but what would happen when there are more classes in a single file? Could be that any missing import in any python file is relatively easy to spot, but sometimes a specific typing for a single function may be faulty or missed in a refactoring.

**Comment by pschanely** [comment]
Thank you for the excellent bug report! I do consider this a bug since ideally internal errors never reach the user.
I was able to reproduce the problem and attempted a fix in 0bf047c0ad51bf70c9a600eb5b8bfe9f609f3f18; would you give this another try and see whether it handles your situation as well? Thanks again!

**Comment by CoenSchalkwijk** [comment]
Gave it a try, didn't get the message, but also not in the current HEAD. Will have to double check and verify again.

Silly question: after pulling a specific branch and then running `sudo python3 setup.py install`, I can assume that the currently available source is installed, right? Nothing remains behind of any previous installation or do I need to do something else in order to be sure of a clean (as possible) installation?

**Comment by pschanely** [comment]
Not a silly question! I believe that `sudo python3 setup.py install` on an updated source tree should give you a good installation, even if you already have a prior version installed. 

Thanks in advance for taking another look!

**Comment by CoenSchalkwijk** [comment]
I had to checkout an older version of my codebase to verify, my results:
Could reproduce the stack dump with b59cee and not with 0bf047

**But!**

I can only use the 'watch' option and wait until something or nothing happens. When using the 'check' option with the b59cee commit I did not get _any_ results on the class that results in the stack dump with the 'watch' command.

So I cannot be absolutely sure it's fixed.

Also, with 0bf047, I did get a nicely captured stack dump, but from crosshair's code, not mine :smile: :

```
I couldn't import a file.
/usr/local/lib/python3.8/dist-packages/crosshair_tool-0.0.7-py3.8.egg/crosshair/util.py:172:
|            try:
|                spec_exists = importlib.util.find_spec(cur_module_name) is not None
|                if not spec_exists:
>                    raise ModuleNotFoundError(f"No module named '{cur_module_name}'")
|            except ModuleNotFoundError:
|                if i == 1:
|                    raise

No module named 'propertyLink'
``` 
Where 'propertyLink' is a class of my own. I think this is a result of the changes for 0bf047 since the missing module is related to the stack dump I get with b59cee.

**Comment by pschanely** [comment]
Hmm! Well, if you have a type name (as a string) that isn't importable, even `crosshair check` should report it. (but now, not as an internal stack trace) So if you are just not seeing anything, there is potentially a different problem.

On the second point, it seems to think propertyLink is a module rather than a class. Are you attempting to run on just a single class? (e.g., something like `crosshair check propertyLink`?) CrossHair will want you to specify the module name in front of it.

If you are willing to describe your setup and command line in more detail, I'd love to try and reproduce what you're seeing!

**Comment by pschanely** [comment]
Closing due to inactivity, but feel free to revive it at will!
