### ISSUE TITLE
Undocumented dependency on tk

### ISSUE THREAD

**Issue by Rik-de-Kort** [pschanely/CrossHair#88]
**Expected vs actual behavior**
After forking the repo I followed the stebs in [contributing](https://crosshair.readthedocs.io/en/latest/contributing.html), but go thte error that tkinter could not be found.

I am on Arch so there's very few packages on my system.`sudo pacman -S tk` solved the problem. Maybe good to document? 

Stack trace for completeness:
````python
Process Process-6: in 1 files.
Traceback (most recent call last):
  File "/home/rik/CrossHair/crosshair/main.py", line 256, in pool_worker_main
    (stats, messages) = pool_worker_process_item(item)
  File "/home/rik/CrossHair/crosshair/main.py", line 242, in pool_worker_process_item
    messages = run_checkables(analyze_module(module, options))
  File "/home/rik/CrossHair/crosshair/core.py", line 739, in run_checkables
    collector.extend(checkable.analyze())
  File "/home/rik/CrossHair/crosshair/core.py", line 667, in analyze
    analysis = analyze_calltree(options, conditions)
  File "/home/rik/CrossHair/crosshair/core.py", line 930, in analyze_calltree
    _ = get_subclass_map()  # ensure loaded
  File "/home/rik/CrossHair/crosshair/type_repo.py", line 52, in get_subclass_map
    members = inspect.getmembers(module, inspect.isclass)
  File "/usr/lib/python3.9/inspect.py", line 351, in getmembers
    value = getattr(object, key)
  File "/home/rik/CrossHair/venv/lib/python3.9/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/home/rik/CrossHair/venv/lib/python3.9/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/rik/CrossHair/venv/lib/python3.9/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
````

**Comment by pschanely** [comment]
Ah - thanks for this! (and thanks for trying out CrossHair!)

Tk shouldn't be required to run CrossHair.

I'll probably try and get an Arch docker image and see whether I can reproduce, and then hopefully make some change to avoid the dependency. More later!

**Comment by Rik-de-Kort** [comment]
Thanks for the response! The only reason `six` is in the environment appears to be because `icontract` requires `asttokens` which in turn requires `six`. It's a bit of a shit because the only reason `six` imports `tkinter` is to check if you have it. However, it only catches an ImportError, so the `UnboundLocalError` that `tkinter` raises is not caught. Definitely sounds like something for upstream.

````bash
(venv) [rik@rik-arch-surface CrossHair]$ pipdeptree -r -p six
six==1.15.0
  - asttokens==2.0.4 [requires: six]
    - icontract==2.5.0 [requires: asttokens>=2,<3]
````
